apiVersion: cluster.alauda.io/v1alpha1
kind: ModulePlugin
metadata:
  annotations:
    cpaas.io/module-name: "product-docs"
    cpaas.io/display-name: '{"en": "Product Docs", "zh": "产品文档"}'
    cpaas.io/built-in-plugin: "true"
  labels:
    cpaas.io/module-type: plugin
    cpaas.io/module-name: product-docs
    cpaas.io/auto-install: "true"
  name: product-docs
spec:
  affinity:
    clusterAffinity:
      matchLabels:
        is-global: "true"
  name: product-docs
  logo: ""
  description:
    en: "Product Docs"
    zh: "产品文档"
  deleteable: false
  labelCluster: "false"
  appReleases:
  - name: product-docs
    chartVersions:
    - name: alauda/chart-product-docs-offline
      releaseName: product-docs
      version: v0.0.1
  mainChart: alauda/chart-product-docs-offline
  upgradeRiskLevel: Low
  upgradeRiskDescription: "对用户已部署的应用无影响."
  upgradeRiskDescriptionEn: "No effect on user-deployed applications."

