apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-docs-offline
  description: 离线产品文档
  annotations:
    gitlab.com/project-slug: alauda/product-docs
    gitlab.com/instance: gitlab-ce.alauda.cn
    acp.cpaas.io/ci-pipeline: alauda/business-build/alauda-dev/doc-build-container-platform,alauda/business-build/alauda-dev/product-docs-offline-build
    goharbor.io/repository-slug: alauda/product-docs-offline,alauda/chart-product-docs-offline
    acp.cpaas.io/owner: ysyou@alauda.io
    acp.cpaas.io/functional-attributes: core
spec:
  type: docs
  lifecycle: production
  owner: apt-idp