{{- if eq .Values.deployMode "online" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service_name: alauda-product-docs
  name: alauda-product-docs
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    service_name: alauda-product-docs
  sessionAffinity: None
  type: ClusterIP
{{- end }}
