apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
        - name: dockerconfig
          secret:
            secretName: build-harbor.kauto.docfj
        - name: build-info
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Mi
  templates:
    - templateRef:
        resolver: katanomi.dev.clustertemplate
        params:
          - name: name
            value: offline-docs-build
      params:
        - name: edition
          value: normal
        - name: product_docs_repo_url
          value: "build-harbor.alauda.cn/alauda/product-docs-offline"
        - name: product_docs_repo_name
          value: "alauda/product-docs-offline"
        - name: product_docs_chart_repo_url
          value: "build-harbor.alauda.cn/alauda/chart-product-docs-offline"
        - name: docs_plugin_repo_url
          value: "https://gitlab-ce.alauda.cn/alauda/artifacts"
        - name: docs_plugin_dir_name
          value: "product-docs"