apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
        - name: dockerconfig
          secret:
            secretName: build-harbor.kauto.docfj
        - name: build-info
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Mi
  templates:
    - templateRef:
        resolver: katanomi.dev.clustertemplate
        params:
          - name: name
            value: online-docs-build
      params:
        - name: mode
          value: prod
        - name: docs_env_app_key
          value: product_docs_online_staging_russian
        - name: product_docs_tag_suffix
          value: -online-russian
        - name: minio_credentials_secret
          value: product-docs-russian-minio-credentials
        - name: docs_prefix
          value: russian
