apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
        - name: dockerconfig
          secret:
            secretName: build-harbor.kauto.docfj
  workspaces:
    - description: >
        This workspace is shared among all the pipeline tasks to read/write
        common resources
      name: source
    - name: dockerconfig
  tasks:
    - name: aggregate-offline-docs
      workspaces:
        - name: source
          workspace: source
      params:
        - name: branch
          value: $(build.git.branch.name)
      taskSpec:
        results:
          - description: Determine whether to push to the remote warehouse
            name: modified-flag
            type: string
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: aggregate-offline-docs
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/aggregate_offline_docs.xsh
            args:
            - --branch=$(params.branch)
            - --result-file=$(results.modified-flag.path)
            env:
              - name: MAIN_REPO_URL
                value: "https://gitlab-ce.alauda.cn/alauda/product-docs"
              - name: MAIN_REPO_NAME
                value: "product-docs"
              - name: MAIN_REPO_BASE
                value: "container_platform"
              - name: MINIO_URL
                valueFrom:
                  secretKeyRef:
                    name: product-docs-minio-credentials
                    key: url
              - name: MINIO_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-minio-credentials
                    key: access-key
              - name: MINIO_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-minio-credentials
                    key: secret-key
              - name: MINIO_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: product-docs-minio-credentials
                    key: bucket
              - name: GH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-github-credentials
                    key: token
              - name: GITLAB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-gitlab-credentials
                    key: token
    - name: build-image
      runAfter:
        - aggregate-offline-docs
      timeout: 30m
      retries: 2
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: extras
          - name: kind
            value: task
          - name: name
            value: buildx
          - name: version
            value: "0.1"
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
      when:
        - input: "$(tasks.aggregate-offline-docs.results.modified-flag)"
          operator: in
          values:
            - "true"
      params:
        - name: context
          value: "."
        - name: dockerfile
          value: ./Dockerfile
        - name: image-url
          value: build-harbor.alauda.cn/alauda/product-docs-offline
        - name: image-tags
          value:
          - $(build.git.version.short)$(build.triggeredBy.triggeredTimestamp.yyyyMMddmmss)
        - name: labels
          value:
            - branch=$(build.git.branch.name)
            - commit=$(build.git.lastCommit.id)
        - name: platform
          value:
            - linux/amd64
            - linux/arm64
    - name: update-module-plugin
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: source
      when:
        - input: "$(tasks.aggregate-offline-docs.results.modified-flag)"
          operator: in
          values:
            - "true"
      params:
        - name: build_tag
          value: $(build.git.version.short)$(build.triggeredBy.triggeredTimestamp.yyyyMMddmmss)
      taskSpec:
        description: |
          set the version
        workspaces:
          - name: source
            workspace: source
        params:
          - name: build_tag
            type: string
        steps:
          - name: set-version
            image: build-harbor.alauda.cn/ops/alpine:latest
            imagePullPolicy: IfNotPresent
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              sed -i "s|version: .*|version: $(params.build_tag)|g" ./chart/module-plugin.yaml
              cat ./chart/module-plugin.yaml
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
    - name: chart-build
      runAfter:
        - update-module-plugin
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: chart-build
      workspaces:
        - name: source
          workspace: source
      when:
        - input: "$(tasks.aggregate-offline-docs.results.modified-flag)"
          operator: in
          values:
            - "true"
      params:
        - name: helm-images
          value:
            - build-harbor.alauda.cn/alauda/chart-product-docs-offline:$(build.git.version.short)$(build.triggeredBy.triggeredTimestamp.yyyyMMddmmss)
        - name: dir
          value: ./chart
        - name: media-type
          value: application/vnd.cncf.helm.chart.content.v1.tar+gzip
        - name: version
          value:
            - chart-version=$(build.git.version.short)$(build.triggeredBy.triggeredTimestamp.yyyyMMddmmss)
        - name: values
          value:
            - global.images.productDocs.repository=alauda/product-docs-offline
            - global.images.productDocs.tag=$(build.git.version.short)$(build.triggeredBy.triggeredTimestamp.yyyyMMddmmss)
            - deployMode=offline
        - name: annotations
          value:
            - branch=$(build.git.branch.name)
            - commit=$(build.git.lastCommit.id)
    - name: clone-artifacts-repo
      runAfter:
        - chart-build
      timeout: 5m
      retries: 3
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: git-url
          value: https://gitlab-ce.alauda.cn/alauda/artifacts
        - name: git-revision
          value: $(build.git.branch.name)
      workspaces:
        - name: source
          workspace: source
    - name: update-chart-version
      runAfter:
        - clone-artifacts-repo
      timeout: 2m
      retries: 0
      taskRef:
        name: yaml-update
        kind: ClusterTask
      params:
        - name: path
          value: ./product-docs/versions.yaml
        - name: set
          value:
            - .default="$(build.git.version.short)$(build.triggeredBy.triggeredTimestamp.yyyyMMddmmss)"
      workspaces:
        - name: source
          workspace: source
    - name: publish-to-artifacts
      runAfter:
        - update-chart-version
      timeout: 5m
      retries: 0
      taskRef:
        name: alauda-git-commit-push
        kind: ClusterTask
      when:
        - input: "$(tasks.update-chart-version.results.push-flag)"
          operator: in
          values:
            - "true"
      params:
        - name: branch
          value: $(build.git.branch.name)
        - name: git-message
          value: "update product-docs version to $(build.git.version.short)$(build.triggeredBy.triggeredTimestamp.yyyyMMddmmss)"
      workspaces:
        - name: source
          workspace: source
  finally:
    - name: release-tag
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: alauda-release-tag
      workspaces:
        - name: source
          workspace: source
      when:
        - input: $(build.git.versionPhase)
          operator: in
          values:
            - custom
            - ga
        - input: $(tasks.status)
          operator: in
          values:
            - Succeeded
            - Completed
      params:
        - name: version
          value: $(build.git.version.short)$(build.triggeredBy.triggeredTimestamp.yyyyMMddmmss)

