apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
  workspaces:
    - description: >
        This workspace is shared among all the pipeline tasks to read/write
        common resources
      name: source
  tasks:
    - name: promote-staging-to-prod-cn
      timeout: 20m
      workspaces:
        - name: source
          workspace: source
      retries: 3
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: promote-staging-to-prod-cn
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/promote_to_prod.xsh
            args:
            - --alauda-console-tag=v3.18.5
            - --product-docs-app-key=product_docs_online_staging
            - --target-apprelease-name=product-docs
            - --target-apprelease-namespace=alaudacloud
            env:
              - name: SOURCE_REGISTRY
                value: registry.alauda.cn:60070
              - name: TARGET_REGISTRY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: address
              - name: TARGET_REGISTRY_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: username
              - name: TARGET_REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: password
              - name: PROD_KUBERNETES_SERVER
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-k8s
                    key: server
              - name: PROD_KUBERNETES_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-k8s
                    key: token
              - name: GITLAB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-gitlab-credentials
                    key: token
    - name: promote-staging-to-prod-cn-russian
      timeout: 20m
      workspaces:
        - name: source
          workspace: source
      retries: 3
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: promote-staging-to-prod-cn
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/promote_to_prod.xsh
            args:
            - --alauda-console-tag=v3.18.5
            - --product-docs-app-key=product_docs_online_staging_russian
            - --target-apprelease-name=product-docs-russian
            - --target-apprelease-namespace=alaudacloud
            env:
              - name: SOURCE_REGISTRY
                value: registry.alauda.cn:60070
              - name: TARGET_REGISTRY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: address
              - name: TARGET_REGISTRY_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: username
              - name: TARGET_REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: password
              - name: PROD_KUBERNETES_SERVER
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-k8s
                    key: server
              - name: PROD_KUBERNETES_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-k8s
                    key: token
              - name: GITLAB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-gitlab-credentials
                    key: token
    - name: promote-staging-to-prod-io
      timeout: 20m
      workspaces:
        - name: source
          workspace: source
      retries: 3
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: promote-staging-to-prod-io
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/promote_to_prod.xsh
            args:
            - --alauda-console-tag=v3.18.5
            - --product-docs-app-key=product_docs_online_staging
            - --target-apprelease-name=product-docs
            - --target-apprelease-namespace=alaudacloud
            env:
              - name: SOURCE_REGISTRY
                value: registry.alauda.cn:60070
              - name: TARGET_REGISTRY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: address
              - name: TARGET_REGISTRY_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: username
              - name: TARGET_REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: password
              - name: PROD_KUBERNETES_SERVER
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-k8s
                    key: server
              - name: PROD_KUBERNETES_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-k8s
                    key: token
              - name: GITLAB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-gitlab-credentials
                    key: token
    - name: promote-staging-to-prod-io-russian
      timeout: 20m
      workspaces:
        - name: source
          workspace: source
      retries: 3
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: promote-staging-to-prod-io
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/promote_to_prod.xsh
            args:
            - --alauda-console-tag=v3.18.5
            - --product-docs-app-key=product_docs_online_staging_russian
            - --target-apprelease-name=product-docs-russian
            - --target-apprelease-namespace=alaudacloud
            env:
              - name: SOURCE_REGISTRY
                value: registry.alauda.cn:60070
              - name: TARGET_REGISTRY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: address
              - name: TARGET_REGISTRY_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: username
              - name: TARGET_REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: password
              - name: PROD_KUBERNETES_SERVER
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-k8s
                    key: server
              - name: PROD_KUBERNETES_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-k8s
                    key: token
              - name: GITLAB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-gitlab-credentials
                    key: token
