apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
        - name: docs-env-source
  workspaces:
    - description: >
        This workspace is shared among all the pipeline tasks to read/write
        common resources
      name: source
    - name: docs-env-source
  tasks:
    - name: clone-docs-env
      timeout: 5m
      workspaces:
        - name: docs-env-source
          workspace: docs-env-source
      retries: 3
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: git-url
          value: https://gitlab-ce.alauda.cn/ops/docs-env
        - name: git-revision
          value: master
    - name: get-latest-staging-version
      runAfter:
        - clone-docs-env
      timeout: 5m
      workspaces:
        - name: docs-env-source
          workspace: docs-env-source
      retries: 3
      results:
        - name: latest-staging-version
          type: string
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/devops/yaml-update:v0.8.0-g025be2e
            name: get-latest-staging-version
            imagePullPolicy: IfNotPresent
            workingDir: $(workspaces.docs-env-source.path)
            script: |
              # set -x
              yq eval '.apps.product_docs_online_staging.version' ./gitops-apps/values.versions.yaml > $(results.latest-staging-version.path)
    - name: prompt-staging-to-prod-cn
      runAfter:
        - get-latest-staging-version
      timeout: 20m
      workspaces:
        - name: source
          workspace: source
      retries: 3
      params:
        - name: product-docs-tag
          value: $(tasks.get-latest-staging-version.results.latest-staging-version)
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: prompt-staging-to-prod-cn
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/prompt_to_prod.xsh
            args:
            - --product-docs-tag=$(params.product-docs-tag)
            - --alauda-console-tag=v3.18.5
            env:
              - name: SOURCE_REGISTRY
                value: registry.alauda.cn:60070
              - name: TARGET_REGISTRY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: address
              - name: TARGET_REGISTRY_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: username
              - name: TARGET_REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-registry
                    key: password
              - name: PROD_KUBERNETES_SERVER
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-k8s
                    key: server
              - name: PROD_KUBERNETES_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-cn-k8s
                    key: token
    - name: prompt-staging-to-prod-io
      runAfter:
        - get-latest-staging-version
      timeout: 20m
      workspaces:
        - name: source
          workspace: source
      retries: 3
      params:
        - name: product-docs-tag
          value: $(tasks.get-latest-staging-version.results.latest-staging-version)
      taskSpec:
        steps:
          - image: build-harbor.alauda.cn/idp/docs-ops:main
            name: prompt-staging-to-prod-io
            imagePullPolicy: Always
            workingDir: $(workspaces.source.path)
            command:
            - xonsh
            - /apps/prompt_to_prod.xsh
            args:
            - --product-docs-tag=$(params.product-docs-tag)
            - --alauda-console-tag=v3.18.5
            env:
              - name: SOURCE_REGISTRY
                value: registry.alauda.cn:60070
              - name: TARGET_REGISTRY
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: address
              - name: TARGET_REGISTRY_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: username
              - name: TARGET_REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-registry
                    key: password
              - name: PROD_KUBERNETES_SERVER
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-k8s
                    key: server
              - name: PROD_KUBERNETES_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: product-docs-io-k8s
                    key: token
