apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pr-manage
  annotations:
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/AlaudaDevops/toolbox/main/pr-cli/pipeline/pr-manage.yaml"
    pipelinesascode.tekton.dev/on-comment: "^/(help|rebase|lgtm|remove-lgtm|cherry-?pick|assign|merge|ready|unassign|label|unlabel|check|retest|close|batch|checkbox|checkbox-issue)($|\\s.*)"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineRef:
    name: pr-manage
  params:
    - name: trigger_comment
      value: "{{ trigger_comment }}"
    - name: repo_owner
      value: "{{ repo_owner }}"
    - name: repo_name
      value: "{{ repo_name }}"
    - name: pull_request_number
      value: "{{ pull_request_number }}"
    - name: comment_sender
      value: "{{ sender }}"
    - name: git_auth_secret
      value: "{{ git_auth_secret }}"
    #
    # Optional parameters (value is the default):
    #
    # The key in git_auth_secret that contains the token (default: git-provider-token)
    # - name: git_auth_secret_key
    #   value: "git-provider-token"
    #
    # Container image for pr-cli tool (default: registry.alauda.cn:60070/devops/toolbox/pr-cli:latest)
    # - name: image
    #   value: "registry.alauda.cn:60070/devops/toolbox/pr-cli:latest"
    #
    # The /lgtm threshold needed of approvers for a PR to be approved (default: 1)
    # - name: lgtm_threshold
    #   value: "1"
    #
    # The permissions the user need to trigger a lgtm (default: admin,write)
    # - name: lgtm_permissions
    #   value: "admin,write"
    #
    # The review event when lgtm is triggered, can be APPROVE,
    # REQUEST_CHANGES, or COMMENT if setting to empty string it will be set as
    # PENDING (default: APPROVE)
    # - name: lgtm_review_event
    #   value: "APPROVE"
    #
    # The merge method to use. Can be one of: merge, squash, rebase (default: squash)
    # - name: merge_method
    #   value: "squash"
    #
    # The name used for self-check status (default: pr-manage)
    # - name: self_check_name
    #   value: "pr-manage"
    #
    # Enable debug mode (skip validation, allow PR creator self-approval) (default: false)
    # - name: debug
    #   value: "false"
    #
    # Enable verbose logging (debug level logs) (default: false)
    # - name: verbose
    #   value: "false"
    #
    # The platform to use, can be one of: github, gitlab, gitee (default: github)
    # - name: platform
    #   value: "github"
    #
    # The robot accounts for managing bot approval reviews.
    # - name: robot_accounts
    #   value: "alaudabot,dependabot,renovate"
